//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffee_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public int seatId { get; set; }
        public string reserver { get; set; }
        public string occupied { get; set; }
        public bool available { get; set; }
        public string place { get; set; }
    }
}
